# Generated by Django 3.0.7 on 2021-01-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='校名')),
                ('intro', models.TextField(verbose_name='简介')),
                ('type', models.CharField(choices=[('pub', '公立'), ('pri', '私立')], default='pub', max_length=3, verbose_name='类型')),
                ('year', models.IntegerField(default=0, verbose_name='创立时间')),
                ('academic_calendar', models.CharField(choices=[('q', '季度制'), ('s', '半年制')], default='s', max_length=1, verbose_name='学期制度')),
                ('website', models.CharField(default='', max_length=200, verbose_name='学校网站')),
                ('ranking', models.TextField(verbose_name='排名')),
                ('images', models.TextField(verbose_name='图片')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
